name: Compress Images
on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      
  workflow_dispatch:
      
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[automated]')"
    name: Compress Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Compress Images
        id: compress
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ignorePaths: "node_modules/**,www/images/icons/**"
          compressOnly: true
          
      - name: Install dependencies
        run: npm install
        
      - name: Update icons
        run: npm run update-icons
        
      - name: Create commit
        run: |
          git add .
          git commit -am "[automated] optimize images\n\n${{steps.compress.outputs.markdown}}"
          git push
    
