name: Compress Images
on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      
  workflow_dispatch:

      
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ignorePaths: "node_modules/**,www/images/icons/**"
          compressOnly: true
          
      - name: Install dependencies
        run: npm install
        
      - name: Update icons
        run: npm run update-icons

            
    
